### ISSUE TITLE
[FEAT] Attachments in PrivateMessage and GuildMessage

### ISSUE THREAD

**Issue by s-liwka** [xXenvy/Pynext#16]
**Describe the solution you'd like**
I would like for the message classes to have a attachments parameter cuz theres no way to retrieve attachments from a message now. Also i'd like "proxied attachments" to be added as seen in this library: https://github.com/Shell1010/Selfcord -- They allow to retrieve attachments a while after a message has been deleted which is really useful

**Comment by xXenvy** [comment]
I don't see "proxied attachment" anywhere in the posted library. Also i don't really understand the point of this since you could retrieve attachments from the old Message object passed in the on_message_delete event.
