### ISSUE TITLE
[FEAT] Add parameter "replies to" to message

### ISSUE THREAD

**Issue by s-liwka** [xXenvy/Pynext#21]
**Describe the solution you'd like**
I have no idea if thats possible but you know that in discord you can reply to a message right? I think there should be a parameter to see if (and if yes then to what) the message is replying.
![image](https://github.com/xXenvy/Pynext/assets/116428267/f645990c-3915-475b-954c-ee9cc2675662)
The message "Response" should have an parameter which points to "Original message"
Then you should be able to interact with "Original message" like with any other message so read contents etc.

**Comment by xXenvy** [comment]
Same as the previous one. References will be available in 1.2.0. Thank you for both suggestions.
